services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/pokerboard
            - NODE_ENV=development
            - NEXTAUTH_URL=http://localhost:3000
            - NEXTAUTH_SECRET=oM9zD94t864o5YSLUCj3w1eC89rtTkVOmXcm7TnWy78=
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        command: npm run dev
        depends_on:
            - db

    db:
        image: postgres:16-alpine
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=pokerboard
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
